version = 1

[[annotations]]
path = ["Manifest*", "Project.toml", ".gitignore"]
SPDX-FileCopyrightText = "2025 Uwe Fechner"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["docs/src/*.png", "docs/src/*.md", "docs/src/*.bib"]
SPDX-FileCopyrightText = "2025 Uwe Fechner"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["README.md", "CHANGELOG.md", "data/*.yaml", "data/2021_9T_Data/*.csv", "data/2021_54T_NordseeOne/*.csv", "data/DTU_10MW/*.*", "examples_dev/README.txt", "test/data/*.mat", ".zenodo.json", "CITATION.cff"]
SPDX-FileCopyrightText = "2025 Marcus Becker, Uwe Fechner"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["docs/src/windfarm-layout-nordsee-one.webp"]
SPDX-FileCopyrightText = "2025 Nordsee One GmbH"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["docs/.gitignore", "docs/Project.toml"]
SPDX-FileCopyrightText = "2025 Uwe Fechner"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["docs/.gitignore", "test/randn.mat"]
SPDX-FileCopyrightText = "2025 Uwe Fechner"
SPDX-License-Identifier = "MIT"
